services:
  app-server:
    container_name: backend-server
    image: varnaa/book-store
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database

  database:
    container_name: db
    image: oscarfonts/h2
    ports:
      - 1521:1521
      - 81:81
    restart: always
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - /Users/varnaa/Documents/db:/opt/h2-data

  cache:
    container_name: redis-cache
    image: redis
    ports:
      - 6379
    restart: always
    depends_on:
      - database
      - app-server