services:
  app-server:
    container_name: backend-server
    image: 'koushik/book-store'
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database

  database:
    container_name: db
    image: 'oscarfonts/h2'
    ports:
      - 1521:1521
      - 81:81
    restart: always
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - C:\Users\Koushik\Desktop\TCL\My bookstore\backend\bookstore\src\main\resources\H2_database:/opt/h2-data

  app-client:
    container_name: bookstore_frontend
    image: 'frontend'
    ports:
      - 8081:80
    restart: always
    depends_on:
      - app-server
      - database
      - cache

  cache:
    container_name: redis-cache
    image: 'redis'
    ports:
      - 6379
    restart: always
    depends_on:
      - database
      - app-server
    command: redis-server --port 6379 --bind 0.0.0.0 --protected-mode no
